apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8c.collection.enabled: "true"
  name: {{ include "sumologic.fullname" . }}-kube-state-metrics
  namespace: {{ $.Release.Namespace }}
spec:
  endpoints:
  - honorLabels: true
    port: http
    metricRelabelings:
    ## kube_daemonset_status_current_number_scheduled
    ## kube_daemonset_status_desired_number_scheduled
    ## kube_daemonset_status_number_misscheduled
    ## kube_daemonset_status_number_unavailable
    ## kube_deployment_spec_replicas
    ## kube_deployment_status_replicas_available
    ## kube_deployment_status_replicas_unavailable
    ## kube_node_info
    ## kube_node_status_allocatable
    ## kube_node_status_capacity
    ## kube_node_status_condition
    ## kube_statefulset_metadata_generation
    ## kube_statefulset_replicas
    ## kube_statefulset_status_observed_generation
    ## kube_statefulset_status_replicas
    ## kube_hpa_spec_max_replicas
    ## kube_hpa_spec_min_replicas
    ## kube_hpa_status_condition
    ## kube_hpa_status_current_replicas
    ## kube_hpa_status_desired_replicas
    ## kube pod state metrics
    ## kube_pod_container_info
    ## kube_pod_container_resource_limits
    ## kube_pod_container_resource_requests
    ## kube_pod_container_status_ready
    ## kube_pod_container_status_restarts_total
    ## kube_pod_container_status_terminated_reason
    ## kube_pod_status_phase
    ## kube_pod_info
    - action: keep
      regex: {{ include "regex.metric.kubeStateMetrics" . }}
      sourceLabels: [ __name__]
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
    - {{ include "kubeStateMetrics.namespace" . }}
  selector:
  {{- if .Values.prometheusSpec.kubeStateMetrics.selector }}
  {{- toYaml .Values.prometheusSpec.kubeStateMetrics.selector | indent 4 }}
  {{- else }}
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  {{- end }}
