apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ include "release.name" . }}-collection-node-exporter
    k8c.collection.enabled: "true"
  name: {{ include "release.name" . }}-collection-node-exporter
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - metricRelabelings:
    ## node exporter metrics
    ## node_cpu_seconds_total
    ## node_load1
    ## node_load5
    ## node_load15
    ## node_disk_io_time_weighted_seconds_total
    ## node_disk_io_time_seconds_total
    ## node_vmstat_pgpgin
    ## node_vmstat_pgpgout
    ## node_memory_MemFree_bytes
    ## node_memory_Cached_bytes
    ## node_memory_Buffers_bytes
    ## node_memory_MemTotal_bytes
    ## node_network_receive_drop_total
    ## node_network_transmit_drop_total
    ## node_network_receive_bytes_total
    ## node_network_transmit_bytes_total
    ## node_filesystem_avail_bytes
    ## node_filesystem_size_bytes
    ## node_filesystem_files_free
    ## node_filesystem_files
    - action: keep
      regex: (?:node_load1|node_load5|node_load15|node_cpu_seconds_total|node_disk_io_time_weighted_seconds_total|node_disk_io_time_seconds_total|node_vmstat_pgpgin|node_vmstat_pgpgout|node_memory_MemFree_bytes|node_memory_Cached_bytes|node_memory_Buffers_bytes|node_memory_MemTotal_bytes|node_network_receive_drop_total|node_network_transmit_drop_total|node_network_receive_bytes_total|node_network_transmit_bytes_total|node_filesystem_avail_bytes|node_filesystem_size_bytes)
      sourceLabels: [__name__]
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: kubernetes_node
    port: metrics
  namespaceSelector:
    matchNames:
    - {{ include "nodeExporter.namespace" . }}
  selector:
  {{- if .Values.prometheusSpec.nodeExporter.selector }}
  {{- toYaml .Values.prometheusSpec.nodeExporter.selector | indent 4 }}
  {{- else }}
    matchLabels:
      app: prometheus-node-exporter
  {{- end }}
