{{- if .Values.prometheusSpec.additionalScrapeConfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sumologic.fullname" . }}-prometheus-scrape-confg
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "sumologic.fullname" . }}-prometheus-scrape-confg
data:
  additional-scrape-configs.yaml: {{ tpl (toYaml .Values.prometheusSpec.additionalScrapeConfigs) $ | b64enc | quote }}
{{- end }}