apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app: {{ include "release.name" . }}
  name: {{ include "release.name" . }}-prometheus
  namespace: {{ .Release.Namespace }}
spec:
{{ include "prometheus.defaultSpec" . | indent 2 }}

  remoteWrite:
{{ include "prometheus.remoteWrite" . | indent 2 }}

{{- if .Values.prometheusSpec.nodeSelector }}
  nodeSelector:
{{ toYaml .Values.prometheusSpec.nodeSelector | indent 4 }}
{{- end }}

{{- if .Values.prometheusSpec.additionalScrapeConfigs }}
  additionalScrapeConfigs:
    name: {{ include "release.name" . }}-prometheus-scrape-confg
    key: additional-scrape-configs.yaml
{{- end }}

{{- if .Values.prometheusSpec.serviceMonitorNamespaceSelector }}
  serviceMonitorNamespaceSelector:
{{ toYaml .Values.prometheusSpec.serviceMonitorNamespaceSelector | indent 4 }}
{{- end }}

{{- if .Values.prometheusSpec.serviceMonitorSelector }}
  serviceMonitorSelector:
{{ toYaml .Values.prometheusSpec.serviceMonitorSelector | indent 4 }}
{{- end }}

{{- if .Values.prometheusSpec.ruleNamespaceSelector }}
  ruleNamespaceSelector:
{{ toYaml .Values.prometheusSpec.ruleNamespaceSelector | indent 4 }}
{{- end }}

{{- if .Values.prometheusSpec.ruleSelector }}
  ruleSelector:
{{ toYaml .Values.prometheusSpec.ruleSelector | indent 4 }}
{{- end }}
